'''self.horizontalLayout = QHBoxLayout(self)
           self.horizontalLayout.setObjectName("horizontalLayout")
           self.gridLayout = QGridLayout()
           self.gridLayout.setObjectName("gridLayout")
           self.defaultImage = QLabel(self)
           self.defaultImage.setText("")
           self.defaultImage.setObjectName("defaultImage")
           self.gridLayout.addWidget(self.defaultImage, 0, 0, 1, 1)
           self.horizontalLayout.addLayout(self.gridLayout)
           self.verticalLayout = QVBoxLayout()
           self.verticalLayout.setObjectName("verticalLayout")
           self.turnModeButton = QPushButton(self)
           sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
           sizePolicy.setHorizontalStretch(0)
           sizePolicy.setVerticalStretch(0)
           sizePolicy.setHeightForWidth(self.turnModeButton.sizePolicy().hasHeightForWidth())
           self.turnModeButton.setSizePolicy(sizePolicy)
           self.turnModeButton.setMaximumSize(QSize(28, 28))
           self.turnModeButton.setObjectName("turnModeButton")
           self.verticalLayout.addWidget(self.turnModeButton, 0, Qt.AlignRight)
           self.horizontalLayout_2 = QHBoxLayout()
           self.horizontalLayout_2.setObjectName("horizontalLayout_2")
           self.searchLine = QLineEdit(self)
           sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
           sizePolicy.setHorizontalStretch(0)
           sizePolicy.setVerticalStretch(0)
           sizePolicy.setHeightForWidth(self.searchLine.sizePolicy().hasHeightForWidth())
           self.searchLine.setSizePolicy(sizePolicy)
           self.searchLine.setObjectName("searchLine")
           self.horizontalLayout_2.addWidget(self.searchLine)
           self.searchImage = QLabel(self)
           sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Preferred)
           sizePolicy.setHorizontalStretch(0)
           sizePolicy.setVerticalStretch(0)
           sizePolicy.setHeightForWidth(self.searchImage.sizePolicy().hasHeightForWidth())
           self.searchImage.setSizePolicy(sizePolicy)
           self.searchImage.setMinimumSize(QSize(24, 24))
           self.searchImage.setText("")
           self.searchImage.setObjectName("searchImage")
           self.horizontalLayout_2.addWidget(self.searchImage)
           self.verticalLayout.addLayout(self.horizontalLayout_2)
           self.horizontalLayout_3 = QHBoxLayout()
           self.horizontalLayout_3.setObjectName("horizontalLayout_3")
           self.systemText = QLabel(self)
           sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Preferred)
           sizePolicy.setHorizontalStretch(0)
           sizePolicy.setVerticalStretch(0)
           sizePolicy.setHeightForWidth(self.systemText.sizePolicy().hasHeightForWidth())
           self.systemText.setSizePolicy(sizePolicy)
           self.systemText.setObjectName("systemText")
           self.horizontalLayout_3.addWidget(self.systemText)
           self.buttonBefore = QPushButton(self)
           self.buttonBefore.setObjectName("buttonBefore")
           self.horizontalLayout_3.addWidget(self.buttonBefore)
           self.buttonAfter = QPushButton(self)
           self.buttonAfter.setObjectName("buttonAfter")
           self.horizontalLayout_3.addWidget(self.buttonAfter)
           self.buttonPeriod = QPushButton(self)
           self.buttonPeriod.setObjectName("buttonPeriod")
           self.horizontalLayout_3.addWidget(self.buttonPeriod)
           self.verticalLayout.addLayout(self.horizontalLayout_3)
           self.dateTime = QDateTimeEdit(self)
           self.dateTime.setObjectName("dateTime")
           self.verticalLayout.addWidget(self.dateTime)
           self.searchResultList = QListView(self)
           sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
           sizePolicy.setHorizontalStretch(0)
           sizePolicy.setVerticalStretch(0)
           sizePolicy.setHeightForWidth(self.searchResultList.sizePolicy().hasHeightForWidth())
           self.searchResultList.setSizePolicy(sizePolicy)
           self.searchResultList.setMaximumSize(QSize(16777215, 150))
           self.searchResultList.setObjectName("searchResultList")
           self.verticalLayout.addWidget(self.searchResultList)
           spacerItem = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)
           self.verticalLayout.addItem(spacerItem)
           self.horizontalLayout.addLayout(self.verticalLayout)
           # MainWindow.setCentralWidget(self)
           # self.menubar = QMenuBar(MainWindow)
           # self.menubar.setGeometry(QtCore.QRect(0, 0, 677, 26))
           # self.menubar.setObjectName("menubar")
           # MainWindow.setMenuBar(self.menubar)
           # self.statusbar = QStatusBar(MainWindow)
           # self.statusbar.setObjectName("statusbar")
           # MainWindow.setStatusBar(self.statusbar)'''
